// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot15.subsystems;

import org.usfirst.frc1073.robot15.Robot;
import org.usfirst.frc1073.robot15.RobotMap;
import org.usfirst.frc1073.robot15.commands.*;

import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Dashboard extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new SendToDashboard());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    
    // Method that returns an int depending on the various combinations of cubic and fieldRel
    private int CubicRel(boolean cubic, boolean fieldRel) {
    	if(!cubic && !fieldRel) {
    		return 0;
    	}
    	else if(cubic && !fieldRel) {
    		return 1;
    	}
    	else if(!cubic && fieldRel) {
    		return 2;
    	}
    	else if(cubic && fieldRel) {
    		return 3;
    	}
    	return -1;
    }
    
    // Method that returns an int for collecting and purging for both tote and bin
    private int collectPunch(boolean collectingTote, boolean purgingTote, boolean collectingBin, boolean purgingBin) {
    	if(collectingTote || collectingBin) {
    		return 0;
    	}
    	else if(purgingTote || purgingBin) {
    		return 1;
    	}
    	return 1;
    }
    
    // Method that sends the data to driver station 
	public void sendData() {
		SmartDashboard.putNumber("Driving Mode", CubicRel(Robot.driveTrain.isCubicDrive(), Robot.driveTrain.isFieldRelative()));
		SmartDashboard.putNumber("Tote Count", Robot.elevator.getTotesHeld());
		SmartDashboard.putNumber("Distance Widget", Robot.rangeFinder.getDistance()); 
		SmartDashboard.putNumber("ToteCollectorInfo", collectPunch(Robot.collectorWheels.isCollecting(), Robot.collectorWheels.isPurging(), Robot.binCollector.isCollecting(), Robot.binCollector.islowering()));
		SmartDashboard.putNumber("Battery", DriverStation.getInstance().getBatteryVoltage());
		SmartDashboard.putBoolean("Claw", Robot.binCollector.getState());
		SmartDashboard.putBoolean("Wrist", Robot.collectorWrists.getState());
		SmartDashboard.putNumber("Elevator Level", Robot.elevator.getPistonState());
		//SmartDashboard.putNumber("Current", )
		
	}
	
	// Method that will put all of the information used while testing
	public void allTestingInformation(){
		Robot.driveTrain.testingInfo();
		Robot.elevator.testingInformation();
		Robot.collectorWrists.testInformation();
	}
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
}

