// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot15.subsystems;

import org.usfirst.frc1073.robot15.RobotMap;
import org.usfirst.frc1073.robot15.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.RobotDrive;


/**
 *
 */
public class DriveTrain extends Subsystem {
	/*
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANJaguar frontR = RobotMap.driveTrainFrontR;
    CANJaguar frontL = RobotMap.driveTrainFrontL;
    CANJaguar backL = RobotMap.driveTrainBackL;
    CANJaguar backR = RobotMap.driveTrainBackR;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    */
	
	CANTalon frontR = RobotMap.driveTrainFrontR;
    CANTalon frontL = RobotMap.driveTrainFrontL;
    CANTalon backL = RobotMap.driveTrainBackL;
    CANTalon backR = RobotMap.driveTrainBackR;
    RobotDrive drive = new RobotDrive(frontR, frontL, backL, backR);
    
	
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
   /**
    * 
    * @param x is the x cord from the joystick
    * @param y is the y cord from the joystick
    * @param z is the rotation from the joystick
    * 
	**/
    public void move(float x, float y, float z){
    	float mag = (float) Math.sqrt(Math.pow(x, 2) + Math.pow(y, 2));
    	float r = (float) Math.atan(y / x);
    	drive.mecanumDrive_Polar(mag, r, z);
    }

    public void initDefaultCommand() {
    	/*
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
		*/
    	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

