// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot15.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc1073.robot15.Robot;

/**
 *
 */
public class  Drive extends Command {

    public Drive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	float x;
    	float y;
    	float twist;
    	
    	//These if statements are to establish a dead zone on the joystick
    	if(Robot.oi.driver.getX() >= 0.05 || Robot.oi.driver.getX() <= -0.05){
    		x = (float) Robot.oi.driver.getX();
    	}
    	else x = 0.0f;
    	
    	if(Robot.oi.driver.getY() >= 0.05 || Robot.oi.driver.getY() <= -0.05){
    		y = (float) Robot.oi.driver.getY();
    	}
    	else y = 0.0f;
    	
		if(Robot.oi.driver.getTwist() >= 0.05 || Robot.oi.driver.getTwist() <= -0.05){
			twist = (float) Robot.oi.driver.getTwist();
		}
		else twist = 0.0f;
		
		//For testing to print on smart dashboard 
    	SmartDashboard.putNumber("The x value is:", x);
    	SmartDashboard.putNumber("The y value is:", y);
    	SmartDashboard.putNumber("The twist value is:", twist);
    	
    	Robot.driveTrain.move(x, y, twist);

    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
