 // RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot15.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc1073.robot15.Robot;

/**
 *
 */
public class  Drive extends Command {

    public Drive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	
    	float x = (float) Robot.oi.driver.getX();
    	float y = (float) Robot.oi.driver.getY();
    	float twist = (float) Robot.oi.driver.getTwist(); 
    	
    	if(Math.abs(x) <= 0.05){
    		x = 0;
    	}
    	if(Math.abs(y) <= 0.05){
    		y = 0;
    	}
    	if(Math.abs(twist) <= 0.30){
    		twist = 0;
    	}
    	
    	Robot.driveTrain.move(x, y, twist);
    	double voltsScale = SmartDashboard.getNumber("voltsPerCM: ");
    	Robot.rangeFinder.changeCMScale(voltsScale);
    	SmartDashboard.putNumber("Distance in CM: ", Robot.rangeFinder.getDistance()); 
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.driveTrain.move(0, 0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
