// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.robot15.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc1073.robot15.Robot;
import org.usfirst.frc1073.robot15.subsystems.Elevator;
import org.usfirst.frc1073.robot15.subsystems.Elevator.elevState;

/**
 *
 */
public class  ToToteFloor extends Command {

    public ToToteFloor() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.binCollector.open();
    	Robot.binCollector.binLift();
    	Robot.collectorWrists.open();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {

    	if (Robot.elevator.elevatorState() == 4) {
    		Robot.elevator.pistonStop();
    		Robot.collectorWheels.wheelsPurge();
    		Robot.elevator.rollersPurge();
    	}
    	else
    	{
        	Robot.elevator.move(elevState.FLOOR_2);
    	}
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	Robot.collectorWheels.wheelsOff();
    	Robot.elevator.rollersOff();
    	Robot.binCollector.close();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	end();
    }
}
